<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
<!-- Generated by NotebookLM Corrected Mindmap Extractor v6.0 with X-Level Parent-Child Logic -->
  <node ID="node_0" TEXT="Deconstructing the Lauren Deal Narrative">
    <node ID="node_1" TEXT="Environmental Contradictions">
      <node ID="node_6" TEXT="Lunar Illumination">
        <node ID="node_17" TEXT="70% Illumination (Gibbous Phase)">
        </node>
        <node ID="node_18" TEXT="Sufficient for navigation without artificial light">
        </node>
        <node ID="node_19" TEXT="Visual orientation exceeding 50 feet">
        </node>
      </node>
      <node ID="node_7" TEXT="The &apos;Darkness&apos; Narrative">
        <node ID="node_20" TEXT="Claimed &apos;complete darkness&apos; to excuse disorientation">
        </node>
        <node ID="node_21" TEXT="Darkness vanishes for vehicle/driver recognition">
        </node>
        <node ID="node_22" TEXT="Selective sensory activation">
        </node>
      </node>
    </node>
    <node ID="node_2" TEXT="Geographic Impossibilities">
      <node ID="node_8" TEXT="Terrain Discrepancies">
        <node ID="node_23" TEXT="Actual: Large, flat, open airfield">
        </node>
        <node ID="node_24" TEXT="Claimed: Woods, brush, and briar bushes">
        </node>
        <node ID="node_25" TEXT="Absence of dense undergrowth">
        </node>
      </node>
      <node ID="node_9" TEXT="Directional Errors">
        <node ID="node_26" TEXT="Route 421 claimed (10 miles away)">
        </node>
        <node ID="node_27" TEXT="Path away from Route 1 leads to airfield, not road">
        </node>
        <node ID="node_28" TEXT="Inconsistent route to reach pickup point">
        </node>
      </node>
    </node>
    <node ID="node_3" TEXT="Witness &amp; Testimony Conflicts">
      <node ID="node_10" TEXT="Identification vs. Concealment">
        <node ID="node_29" TEXT="Distinguished car vs. truck silhouette">
        </node>
        <node ID="node_30" TEXT="Identified specific driver (Joseph)">
        </node>
        <node ID="node_31" TEXT="Mutual visibility and eye contact">
        </node>
      </node>
      <node ID="node_11" TEXT="DeMarco Interview">
        <node ID="node_32" TEXT="Claimed seeing her from the road near Route 1">
        </node>
        <node ID="node_33" TEXT="Contradicts hiding/concealment claims">
        </node>
      </node>
    </node>
    <node ID="node_4" TEXT="Physiological Implausibility">
      <node ID="node_12" TEXT="Physical Condition">
        <node ID="node_34" TEXT="BMI of 31.9 (Obesity)">
        </node>
        <node ID="node_35" TEXT="Impaired by alcohol consumption">
        </node>
        <node ID="node_36" TEXT="History of smoking and lack of activity">
        </node>
      </node>
      <node ID="node_13" TEXT="Performance Claims">
        <node ID="node_37" TEXT="Allegedly outran fit soldiers">
        </node>
        <node ID="node_38" TEXT="Sustained run on uneven terrain">
        </node>
        <node ID="node_39" TEXT="Stumbling and poor balance shown on video">
        </node>
      </node>
    </node>
    <node ID="node_5" TEXT="Investigative Failures">
      <node ID="node_14" TEXT="Ignored narrative drift">
      </node>
      <node ID="node_15" TEXT="Unchecked behavior toggling (hiding vs. waving)">
      </node>
      <node ID="node_16" TEXT="Conscious narrative management by prosecution">
      </node>
    </node>
  </node>
</map>