<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
<!-- Generated by NotebookLM Corrected Mindmap Extractor v6.0 with X-Level Parent-Child Logic -->
  <node ID="node_0" TEXT="Evidence Network Analysis: Benjamin Allen Case">
    <node ID="node_1" TEXT="Medical &amp; Forensic Evidence">
      <node ID="node_6" TEXT="SANE Findings">
        <node ID="node_20" TEXT="Abnormal dye uptake at posterior fourchette">
        </node>
        <node ID="node_21" TEXT="Normal labia minora, hymen, and vagina">
        </node>
        <node ID="node_22" TEXT="No visible lacerations or discharge">
        </node>
        <node ID="node_23" TEXT="Cervical ectropion (non-assault related)">
        </node>
      </node>
      <node ID="node_7" TEXT="DNA &amp; Laboratory Results">
        <node ID="node_24" TEXT="No spermatozoa present in SBI report">
        </node>
        <node ID="node_25" TEXT="ALS black light exam negative for fluorescence">
        </node>
        <node ID="node_26" TEXT="YSTR DNA cannot individuate defendant">
        </node>
        <node ID="node_27" TEXT="Insufficient male DNA for STR amplification">
        </node>
      </node>
      <node ID="node_8" TEXT="Pre-existing Conditions">
        <node ID="node_28" TEXT="Hidradenitis suppurativa (HS) in external areas">
        </node>
        <node ID="node_29" TEXT="Patient disclosed redness but not HS diagnosis">
        </node>
      </node>
    </node>
    <node ID="node_2" TEXT="Complainant Testimony Evolution">
      <node ID="node_9" TEXT="Initial Accounts (Active Resistance)">
        <node ID="node_30" TEXT="Triage: &apos;I pushed him off of me and I ran&apos;">
        </node>
        <node ID="node_31" TEXT="SANE: Narrative of physical escape">
        </node>
        <node ID="node_32" TEXT="Haines: &apos;I did everything I could to get away&apos;">
        </node>
      </node>
      <node ID="node_10" TEXT="Trial Account (Passive Response)">
        <node ID="node_33" TEXT="Introduction of &apos;tonic freeze&apos; narrative">
        </node>
        <node ID="node_34" TEXT="Claimed inability to move or comprehend">
        </node>
        <node ID="node_35" TEXT="Alleged coaching in courthouse lobby">
        </node>
      </node>
      <node ID="node_11" TEXT="Mental Injury &amp; Impact">
        <node ID="node_36" TEXT="Post-assault functional impairment">
        </node>
        <node ID="node_37" TEXT="Loss of trust and identification of triggers">
        </node>
        <node ID="node_38" TEXT="Relocation to different state">
        </node>
      </node>
    </node>
    <node ID="node_3" TEXT="Investigative Conduct &amp; Gaps">
      <node ID="node_12" TEXT="Detective Freeman Issues">
        <node ID="node_39" TEXT="Undisclosed relationship to witness Carmen Love">
        </node>
        <node ID="node_40" TEXT="False denial of ties to Morrison and West">
        </node>
        <node ID="node_41" TEXT="Inaccurate probable cause affidavit timestamps">
        </node>
      </node>
      <node ID="node_13" TEXT="Officer Haines Issues">
        <node ID="node_42" TEXT="Premature commitment to prosecute">
        </node>
        <node ID="node_43" TEXT="Failure to interview daughter present at home">
        </node>
        <node ID="node_44" TEXT="Did not inquire about consent during interview">
        </node>
      </node>
      <node ID="node_14" TEXT="Procedural Failures">
        <node ID="node_45" TEXT="Warrantless arrest without documented cause">
        </node>
        <node ID="node_46" TEXT="Blank witnesses field on Magistrate Order">
        </node>
      </node>
    </node>
    <node ID="node_4" TEXT="Timeline &amp; Physical Impossibilities">
      <node ID="node_15" TEXT="Video Evidence Contradictions">
        <node ID="node_47" TEXT="Carmen Love left 1 hour before 2:00 AM claim">
        </node>
        <node ID="node_48" TEXT="38-minute window from bar to hospital arrival">
        </node>
        <node ID="node_49" TEXT="Insufficient time for drive, assault, and escape">
        </node>
      </node>
      <node ID="node_16" TEXT="Scene Reconstruction Issues">
        <node ID="node_50" TEXT="Disputed bonfire location (front vs. back yard)">
        </node>
        <node ID="node_51" TEXT="Availability of three alternative house exits">
        </node>
        <node ID="node_52" TEXT="Hiding at airfield vs. bushes/woods">
        </node>
      </node>
    </node>
    <node ID="node_5" TEXT="Legal Motions &amp; Verdicts">
      <node ID="node_17" TEXT="Franks &amp; Suppression">
        <node ID="node_53" TEXT="Challenge to reckless disregard for truth">
        </node>
        <node ID="node_54" TEXT="Motion to suppress derivative evidence">
        </node>
      </node>
      <node ID="node_18" TEXT="Prosecutorial Misconduct">
        <node ID="node_55" TEXT="False representations of DNA &apos;matches&apos;">
        </node>
        <node ID="node_56" TEXT="Claim of &apos;major vaginal damage&apos; vs. records">
        </node>
        <node ID="node_57" TEXT="Omission of acquittal from official filings">
        </node>
      </node>
      <node ID="node_19" TEXT="Jury Verdict (July 2023)">
        <node ID="node_58" TEXT="Unanimous 12-0 acquittal on 1st Degree Rape">
        </node>
        <node ID="node_59" TEXT="9-3 split on 2nd Degree (majority acquittal)">
        </node>
      </node>
    </node>
  </node>
</map>