<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
<!-- Generated by NotebookLM Corrected Mindmap Extractor v6.0 with X-Level Parent-Child Logic -->
  <node ID="node_0" TEXT="State vs. Ben Allen: Perjury and Misconduct Analysis">
    <node ID="node_1" TEXT="Lauren Deal Testimony Contradictions">
      <node ID="node_5" TEXT="Social Interaction at Bar">
        <node ID="node_16" TEXT="Claim: Friendly immediate hug">
        </node>
        <node ID="node_17" TEXT="Video: No hug upon arrival">
        </node>
        <node ID="node_18" TEXT="Claim: Hours of group drinking">
        </node>
        <node ID="node_19" TEXT="Video: Friends left an hour before interaction">
        </node>
      </node>
      <node ID="node_6" TEXT="The Bedroom &apos;Lure&apos;">
        <node ID="node_20" TEXT="Claim: No TP in guest bathroom">
        </node>
        <node ID="node_21" TEXT="Fact: 3 available bathrooms; fully stocked">
        </node>
      </node>
      <node ID="node_7" TEXT="Physical Assault Mechanics">
        <node ID="node_22" TEXT="Claim: One-handed restraint of both arms">
        </node>
        <node ID="node_23" TEXT="Fact: Biomechanical impossibility with fitted leggings">
        </node>
        <node ID="node_24" TEXT="Timeline: Sequence exceeds 5-minute window">
        </node>
        <node ID="node_25" TEXT="Physical State: Defendant had broken finger">
        </node>
      </node>
      <node ID="node_8" TEXT="The &apos;Pants Paradox&apos;">
        <node ID="node_26" TEXT="Claim: Removed forcibly on bed">
        </node>
        <node ID="node_27" TEXT="Fact: Pants recovered later in bathroom/woods">
        </node>
        <node ID="node_28" TEXT="Fabrication: Claimed pants were burned in bonfire">
        </node>
      </node>
    </node>
    <node ID="node_2" TEXT="Investigative Malfeasance">
      <node ID="node_9" TEXT="Detective Steve Freeman">
        <node ID="node_29" TEXT="Undisclosed conflict: Family tie to Carmen Love">
        </node>
        <node ID="node_30" TEXT="False testimony: Warrant vs. warrantless arrest">
        </node>
        <node ID="node_31" TEXT="Failure to process crime scene">
        </node>
        <node ID="node_32" TEXT="Strategic delay in DNA testing">
        </node>
      </node>
      <node ID="node_10" TEXT="Probable Cause Failures">
        <node ID="node_33" TEXT="Arrest based on uncorroborated hearsay">
        </node>
        <node ID="node_34" TEXT="Lack of written documentation/affidavit">
        </node>
        <node ID="node_35" TEXT="Disregard for exculpatory bar video">
        </node>
      </node>
    </node>
    <node ID="node_3" TEXT="Narrative Engineering &amp; Coaching">
      <node ID="node_11" TEXT="Forensic Linguistic Analysis">
        <node ID="node_36" TEXT="Stable function words vs. shifting content">
        </node>
        <node ID="node_37" TEXT="Evolution from &apos;resistance&apos; to &apos;freeze&apos; response">
        </node>
        <node ID="node_38" TEXT="Late insertion of legal &apos;fear&apos; elements">
        </node>
      </node>
      <node ID="node_12" TEXT="Prosecutorial Misconduct">
        <node ID="node_39" TEXT="ADA Bartholomew overheard coaching witness">
        </node>
        <node ID="node_40" TEXT="Instruction to claim &apos;fear of witnesses&apos;">
        </node>
        <node ID="node_41" TEXT="Late-stage theory shift to &apos;mental injury&apos;">
        </node>
      </node>
    </node>
    <node ID="node_4" TEXT="Objective Evidence Discrepancies">
      <node ID="node_13" TEXT="Medical Records">
        <node ID="node_42" TEXT="Triage: Patient &apos;content and relaxed&apos;">
        </node>
        <node ID="node_43" TEXT="Pain score: Zero">
        </node>
        <node ID="node_44" TEXT="Radiology: No acute injuries/fractures">
        </node>
      </node>
      <node ID="node_14" TEXT="Environmental Factors">
        <node ID="node_45" TEXT="Visibility: 75% lunar illumination vs. &apos;pitch black&apos;">
        </node>
        <node ID="node_46" TEXT="Terrain: Clear airfield vs. briar-filled woods">
        </node>
      </node>
      <node ID="node_15" TEXT="Extortion Allegation">
        <node ID="node_47" TEXT="$150,000 demand to drop charges ignored">
        </node>
      </node>
    </node>
  </node>
</map>