(() => {
  const KEY='edifice-local-notes-v1'; let notes=[], draft=null, selectedText='', selectionAnchor='', returnFocus=null, cardFilter='', showAll=false;
  try { const data=JSON.parse(localStorage.getItem(KEY)||'[]'); if(Array.isArray(data))notes=data; } catch {}
  const style=document.createElement('link');style.rel='stylesheet';style.href='shared/site-notes.css?v=20261003b';document.head.append(style);
  const notesMount=document.querySelector('[data-site-notes-mount]');
  const launcher=notesMount||document.createElement('button');launcher.classList.add('site-notes-launcher');launcher.type='button';
  if(notesMount)launcher.classList.add('is-inline'); else {launcher.textContent='My Notes';document.body.append(launcher);}
  const selectionButton=document.createElement('button');selectionButton.className='site-note-selection';selectionButton.type='button';selectionButton.textContent='Add note to selected text';selectionButton.hidden=true;document.body.append(selectionButton);
  const dialog=document.createElement('dialog');dialog.className='site-notes-dialog';dialog.setAttribute('aria-labelledby','site-notes-title');
  dialog.innerHTML='<header><h2 id="site-notes-title">My Notes</h2><button type="button" id="notes-close" aria-label="Close notes">×</button></header><p class="notes-help">Personal working notes saved in this browser. They are separate from the website’s case analysis. Export a backup before clearing browser data.</p><form id="notes-form"><blockquote id="notes-quote" hidden></blockquote><label for="notes-text">Add a note</label><textarea id="notes-text" rows="5" maxlength="20000" placeholder="Add context, a question, or something to investigate…" required></textarea><div class="notes-actions"><button type="submit">Save note</button><button type="button" id="notes-new">New note</button><button type="button" id="notes-export">Export all notes</button></div></form><p id="notes-status" role="status"></p><div class="notes-actions"><button type="button" id="notes-all">All saved notes</button><button type="button" id="notes-page">This page or file</button></div><h3 id="notes-scope">Notes for this page or file</h3><div id="notes-list"></div>';
  document.body.append(dialog);const $=id=>dialog.querySelector('#'+id);
  function target(){const file=new URLSearchParams(location.hash.slice(1)).get('file');return file?'file:'+file:'page:'+location.pathname.replace('/assets/pages/','/');}
  function persist(){try{localStorage.setItem(KEY,JSON.stringify(notes));return true;}catch{$('notes-status').textContent='The browser could not save this note. Export your notes to keep a copy.';return false;}}
  function render(){const list=$('notes-list');list.replaceChildren();const matches=notes.filter(n=>showAll||(n.target===target()&&(!cardFilter||n.anchor===cardFilter)));$('notes-scope').textContent=showAll?'All saved notes':cardFilter?'Notes attached to this card':'Notes for this page or file';document.querySelectorAll('[data-card-notes]').forEach(b=>{const count=notes.filter(n=>n.target===target()&&n.anchor===b.dataset.cardNotes).length;b.textContent='▤'+(count?' '+count:'');b.title=count?'Open '+count+' attached notes':'Add a note to this card';b.setAttribute('aria-label',b.title);});launcher.textContent=(notesMount?'Notes':'My Notes')+(matches.length?' ('+matches.length+')':'');
    if(!matches.length){const p=document.createElement('p');p.textContent='No notes saved for this page or file yet.';list.append(p);}
    for(const n of matches){const article=document.createElement('article');article.className='saved-note';const locationLabel=document.createElement('p');locationLabel.textContent=(n.anchor?'Attached to: '+(document.getElementById(n.anchor)?.querySelector('.card-title')?.textContent||n.anchor):'Page note')+' · '+(n.page||n.target);article.append(locationLabel);if(n.quote){const q=document.createElement('blockquote');q.textContent=n.quote;article.append(q);}const text=document.createElement('p');text.textContent=n.text;article.append(text);const stamp=document.createElement('small');stamp.textContent=new Date(n.updated).toLocaleString();article.append(stamp);const actions=document.createElement('div');actions.className='notes-actions';
      const edit=document.createElement('button');edit.type='button';edit.textContent='Edit';edit.onclick=()=>{draft=n;$('notes-text').value=n.text;$('notes-quote').textContent=n.quote||'';$('notes-quote').hidden=!n.quote;$('notes-text').focus();};
      const remove=document.createElement('button');remove.type='button';remove.textContent='Delete';remove.onclick=()=>{const before=notes;notes=notes.filter(x=>x.id!==n.id);if(!persist()){notes=before;return;}render();$('notes-status').textContent='Note deleted.';};actions.append(edit,remove);article.append(actions);list.append(article);
    }
  }
  function open(quote='',anchor=''){cardFilter=anchor;showAll=false;returnFocus=document.activeElement;draft={target:target(),quote,anchor,page:location.pathname,file:new URLSearchParams(location.hash.slice(1)).get('file')||null};$('notes-text').value='';$('notes-quote').textContent=quote;$('notes-quote').hidden=!quote;$('notes-status').textContent='';render();dialog.showModal();selectionButton.hidden=true;$('notes-text').focus();}
  function close(){dialog.close();returnFocus?.focus();}
  launcher.onclick=()=>{open();showAll=true;render();};$('notes-all').onclick=()=>{showAll=true;cardFilter='';render();};$('notes-page').onclick=()=>{showAll=false;cardFilter='';render();};selectionButton.onpointerdown=e=>e.preventDefault();selectionButton.onclick=()=>open(selectedText,selectionAnchor);
  $('notes-close').onclick=close;dialog.addEventListener('close',()=>returnFocus?.focus());$('notes-new').onclick=()=>{draft={target:target(),page:location.pathname,file:new URLSearchParams(location.hash.slice(1)).get('file')||null,quote:''};$('notes-text').value='';$('notes-quote').hidden=true;$('notes-text').focus();};
  $('notes-form').onsubmit=e=>{e.preventDefault();const text=$('notes-text').value.trim();if(!text)return;const current={...draft,id:draft.id||crypto.randomUUID(),text,updated:new Date().toISOString()};const before=notes;notes=[...notes.filter(n=>n.id!==current.id),current];if(!persist()){notes=before;return;}draft={target:target(),page:location.pathname,anchor:cardFilter,quote:''};$('notes-text').value='';$('notes-quote').hidden=true;render();$('notes-status').textContent='Note saved in this browser.';};
  $('notes-export').onclick=()=>{const blob=new Blob([JSON.stringify({format:'edifice-local-notes-v1',exportedAt:new Date().toISOString(),notes},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='case-website-notes-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  document.addEventListener('selectionchange',()=>{if(dialog.open)return;const selection=getSelection();selectedText=selection?.toString().trim().slice(0,5000)||'';const element=selection?.anchorNode?.parentElement;if(!selectedText||!element||element.closest('button,input,textarea,dialog')){selectionButton.hidden=true;return;}selectionAnchor=element.closest('article.card[id]')?.id||element.closest('[id]')?.id||'';selectionButton.hidden=false;});
  function fileButton(){const context=document.getElementById('case-context');if(context&&!context.querySelector('.add-file-note')){const b=document.createElement('button');b.className='add-file-note';b.type='button';b.textContent='Add my note about this evidence';b.onclick=()=>open();context.append(b);}render();}
  for(const card of document.querySelectorAll('article.card[id]')){const b=document.createElement('button');b.type='button';b.className='card-note-icon card-personal-note-icon';b.dataset.cardNotes=card.id;b.onclick=()=>open('',card.id);card.append(b);}
  fileButton();window.addEventListener('hashchange',fileButton);document.addEventListener('evidence-file-selected',fileButton);window.addEventListener('storage',e=>{if(e.key===KEY){try{notes=JSON.parse(e.newValue||'[]');render();}catch{}}});
})();
